### ISSUE TITLE
Add creation/modification of startup.cmd file

### ISSUE THREAD

**Issue by mikecousins** [mikecousins/newrelicazurenuget#1]

**Comment by nickfloyd** [comment]
I did the first part of this... just need to probably gather a few parms from the user to get this item done.

**Comment by mikecousins** [comment]
So my concern here is: Do we need to consider a user that has a startup.cmd file already? I can think of a couple situations that might cause issues here.
1. The user has never used New Relic but is using a startup.cmd file for something else.
2. User has New Relic already installed and has modified the startup file to also run something else. They will lose their license key on upgrade as well right?

Possible fixes include renaming startup.cmd to newrelic.cmd and adding a comment saying that it will be overwritten. This should cause less conflicts. Or we could write a fancier script to merge the existing startup.cmd with a new one, saving their modifications and license key?

What do you think? I ran into these issues before and decided to sit on it for a while!

Nick Floyd reply@reply.github.com wrote:

I did the first part of this... just need to probably gather a few parms from the user to get this item done.

---

**Comment by nickfloyd** [comment]
Thats really solid perspective.  The last thing I think we want to do is frustrate the dev with overwriting anything.  I like idea of making a totally separate one - event to the extent that it is explicitly named something that would never trample on anything if it were overwritten.

I'll work on a few scenarios where the app has existing startup.cmd and without just to get a feel for what might be the best experience given your ideas.

**Comment by nickfloyd** [comment]
Addressed with  : https://github.com/mikecousins/newrelicazurenuget/pull/9
