### ISSUE TITLE
ServiceDefinition project is hardcoded and could be incorrect

### ISSUE THREAD

**Issue by mikecousins** [mikecousins/newrelicazurenuget#11]
The project that we look for the ServiceDefinition file in is hardcoded as <ProjectName>.Azure.  This won't work for many solutions.  For instance in my case I use <ProductName>.Web for the web project and <ProductName>.Azure for the Azure project.  This means that the script is trying to modify the ServiceDefinition file in <ProductName>.Web.Azure which doesn't exist.

**Comment by nickfloyd** [comment]
Hey Mike,

Did I correct this with the last pull request?  Which line of code (if it still exists) does it check for that?

**Comment by mikecousins** [comment]
This is now corrected.

-----Original Message-----
